"""Adding org_id to the spatial_data table

Revision ID: 8261e3378fff
Revises: 1b9591aa6287
Create Date: 2023-12-26 19:42:56.197628

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8261e3378fff'
down_revision: Union[str, None] = '1b9591aa6287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spatial_data', sa.Column('org_id', sa.Integer(), nullable=False))
    op.drop_column('spatial_data', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spatial_data', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_column('spatial_data', 'org_id')
    # ### end Alembic commands ###
